image: archlinux:latest

stages:
  - test

before_script:
  - pacman -Syu --needed --noconfirm rust gcc pkg-config
  - rustc --version
  - cargo --version

format:
  stage: test
  script:
    - cargo fmt --all -- --check

clippy:
  stage: test
  script:
    - cargo clippy --all -- -D warnings

check:
  stage: test
  script:
    - cargo check --all --verbose --release

test:
  stage: test
  script:
    - cargo test --all --verbose --release
